### ISSUE TITLE
Dummy App cannot be created [NEEDS FIX]

### ISSUE THREAD

**Issue by poudelprakash** [TruemarkDev/spree-html-invoice#1]
``` 
bundle exec rake extension:test_app
rake aborted!
LoadError: cannot load such file --
/Users/prakash/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/prakash/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
Tasks: TOP => common:test_app
(See full trace by running task with --trace)
```

This issue also prevents running tests in this repo:

```
bundle exec rspec spec

An error occurred while loading ./spec/controllers/spree/admin/invoice_controller_spec.rb.
Failure/Error: require File.expand_path('../dummy/config/environment.rb',  __FILE__)

LoadError:
  cannot load such file -- /Users/prakash/workspaces/2020/ecom/spree-html-invoice/spec/dummy/config/environment.rb
# ./spec/spec_helper.rb:7:in `require'
# ./spec/spec_helper.rb:7:in `<top (required)>'
# ./spec/controllers/spree/admin/invoice_controller_spec.rb:1:in `require'
# ./spec/controllers/spree/admin/invoice_controller_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 0.30152 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Coverage report generated for RSpec to /Users/prakash/workspaces/2020/ecom/spree-html-invoice/coverage. 0 / 89 LOC (0.0%) covered.
SimpleCov failed with exit 1
```

**Comment by shradhaN** [comment]
@poudelprakash To create the dummy application, instead for running `bundle exec rake extension:test_app`, run `bundle exec rake test_app` which will create the dummy application.

After creation of the dummy application running `bundle exec rspec spec` will generate error
```
 Failure/Error: expect(response).to render_template(:invoice)
     
     NoMethodError:
       assert_template has been extracted to a gem. To continue using it,
               add `gem 'rails-controller-testing'` to your Gemfile.
```

It can be fixed by adding the `gem 'rails-controller-testing` in the Gemfile.

**Comment by shradhaN** [comment]
@poudelprakash Also noticed that this extension could use a `spree_dev_tools` update and the spree support is till version `3.7`. Does this need to be updated?

**Comment by poudelprakash** [comment]
Thank you @shradhaN for filling up the required details for task, 
We are currently using https://github.com/spree-contrib/spree_print_invoice. So, we will revisit this repo only if/when it will be useful.
